// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
)

// InitializeApp 由 Wire 根据 wire.go 生成 —— 对照阅读 v5 的 main.go。
//
// v5 手写：
//
//	db := newMemDB()
//	userRepo := NewUserRepository(db)
//	...
//	r := NewRouter(Dependencies{...})
//
// 下面生成结果几乎一一对应，只是换 Wire 帮你写。
func InitializeApp() *gin.Engine {
	memDB := newMemDB()
	userRepository := NewUserRepository(memDB)
	sessionRepository := NewSessionRepository(memDB)
	authService := NewAuthService(userRepository, sessionRepository)
	projectRepository := NewProjectRepository(memDB)
	projectService := NewProjectService(projectRepository)
	dependencies := provideDependencies(authService, projectService)
	engine := NewRouter(dependencies)
	return engine
}
